### ISSUE TITLE
everdev contract decode-data error: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by asnov** [tonlabs/everdev#117]
Hi
I compiled a contract and deployed it to the network.
Now I'm trying to decode data from a contract deployed on the network.
With any possible arguments it gives me the same error `TypeError: Cannot read property 'length' of undefined`:
```
everdev c dd container.abi.json 
TypeError: Cannot read property 'length' of undefined
```
or
```
everdev c dd container.abi.json -n main -a 0:eb5421848ecc9129a5c16fbec91395bc495e38327f7cdc4d80560c25e654c55f
TypeError: Cannot read property 'length' of undefined
```

**Comment by Artem-Zhdanov** [comment]
I'm closing this issue as irreproducible. There must have been an error installing npm packages.
