### ISSUE TITLE
Error: Giver <wc:address> has unknown code hash

### ISSUE THREAD

**Issue by ilyar** [tonlabs/everdev#94]
https://github.com/tonlabs/evernode-se/commit/365d6bab83b756f7dcf4b4dd9a215988329bf5e5

for compiler `v0.59.1`  code hash is `cca210b159ff5331643bf5b4537b37b0a68543a0704771763ed847933ceab369`

https://github.com/tonlabs/everdev/blob/5ca87885b9120afcb2637285fb6282ef1eb3c77c/src/core/known-contracts.ts#L64-L65

```shell
npx everdev network giver se <wc:address> --signer giver
Error: Giver <wc:address> has unknown code hash <code_hash>
```

To solve this problem, there are several options:

- add new hash codes (which may be different if the developer collects the contract on his own)
- remove the restriction for the giver contract
- add option force adding

🤲🟦🟥

**Comment by Riola7** [comment]
0x30551ac03453360EbbAE55238C39662Ba5EC944E

**Comment by elasticLove1** [comment]
Thank you for your contribution! We released your proposed changes in 1.2.0 version

**Comment by Riola7** [comment]
0x30551ac03453360EbbAE55238C39662Ba5EC944E

Pada tanggal Rab, 1 Jun 2022 04:12, Ekaterina Pantaz <
***@***.***> menulis:

**Comment by ilyar** [comment]
Fixed
